<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Scaffold\ScaffoldGeneratorBlueprintFactory;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Str;
use JsonException;
use RuntimeException;

class MakeModuleScaffoldCommand extends Command
{
    protected $signature = 'make:module-scaffold
        {module : Module name, for example Billing or KnowledgeBase}
        {resource? : Optional singular CRUD resource to scaffold inside the module}
        {--description= : Optional module description}
        {--author= : Optional module author}
        {--homepage= : Optional module homepage}
        {--icon= : Optional module icon markup}
        {--resource-plural= : Optional plural label override for the generated scaffold resource}
        {--route-prefix= : Optional route prefix override for the generated scaffold resource}
        {--permission-prefix= : Optional permission prefix override for the generated scaffold resource}
        {--write : Write the generated module shell and optional scaffold files}
        {--force : Overwrite existing module shell files when possible}
        {--base-path= : Optional base path override, intended for testing sandboxes}
        {--json : Output the generation plan as JSON}';

    protected $description = 'Generate the canonical module shell and optionally a scaffold CRUD resource inside it';

    public function __construct(
        private readonly ScaffoldGeneratorBlueprintFactory $blueprints,
        private readonly Filesystem $files,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $module = Str::studly((string) $this->argument('module'));
        $resource = $this->argument('resource');
        $resourceName = is_string($resource) && trim($resource) !== ''
            ? Str::studly(trim($resource))
            : null;

        $payload = $this->buildPayload($module, $resourceName);

        if ($this->option('write')) {
            $payload['write_result'] = $this->writeModuleShell($payload);

            if ($resourceName !== null) {
                $payload['scaffold_write_result'] = $this->writeScaffoldResource($module, $resourceName);
            }
        }

        if ($this->option('json')) {
            try {
                $this->line(json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR));
            } catch (JsonException $exception) {
                $this->error($exception->getMessage());

                return self::FAILURE;
            }

            return self::SUCCESS;
        }

        $this->table(['Key', 'Value'], [
            ['module', $payload['module']],
            ['slug', $payload['slug']],
            ['module_path', $payload['module_path']],
            ['provider', $payload['provider']],
            ['resource', $resourceName ?? '—'],
        ]);

        $this->newLine();
        $this->info('Module shell files');
        $this->table(
            ['Type', 'Path'],
            collect($payload['files'])
                ->map(fn (string $path, string $type): array => [$type, $path])
                ->values()
                ->all(),
        );

        if (is_array($payload['scaffold_blueprint'] ?? null)) {
            $this->newLine();
            $this->info('Nested scaffold blueprint');
            $this->table(['Key', 'Value'], [
                ['entity_name', $payload['scaffold_blueprint']['entity_name']],
                ['route_prefix', $payload['scaffold_blueprint']['route_prefix']],
                ['permission_prefix', $payload['scaffold_blueprint']['permission_prefix']],
            ]);
        }

        $this->newLine();
        $this->line($this->option('write')
            ? sprintf('<info>Module scaffold written to [%s].</info>', $payload['module_path'])
            : '<comment>Preview only. Re-run with --write to materialize the module scaffold.</comment>');

        return self::SUCCESS;
    }

    /**
     * @return array<string, mixed>
     */
    private function buildPayload(string $module, ?string $resourceName): array
    {
        $slug = Str::kebab($module);
        $modulePath = $this->modulePath($module);
        $namespace = 'Modules\\'.$module.'\\';
        $provider = 'Modules\\'.$module.'\\Providers\\'.$module.'ServiceProvider';
        $pageRoot = $modulePath.'/resources/js/pages/'.$slug;
        $routeFiles = [
            'web' => $modulePath.'/routes/web.php',
        ];

        return [
            'module' => $module,
            'slug' => $slug,
            'description' => $this->stringOption('description') ?? sprintf('%s module scaffold generated by make:module-scaffold.', $module),
            'author' => $this->stringOption('author'),
            'homepage' => $this->stringOption('homepage'),
            'icon' => $this->stringOption('icon'),
            'namespace' => $namespace,
            'provider' => $provider,
            'provider_path' => $modulePath.'/app/Providers/'.$module.'ServiceProvider.php',
            'module_path' => $modulePath,
            'page_root' => $pageRoot,
            'route_files' => $routeFiles,
            'abilities_path' => $modulePath.'/config/abilities.php',
            'navigation_path' => $modulePath.'/config/navigation.php',
            'database_seeder' => $namespace.'Database\\Seeders\\DatabaseSeeder',
            'database_seeder_path' => $modulePath.'/database/seeders/DatabaseSeeder.php',
            'files' => [
                'manifest' => $modulePath.'/module.json',
                'provider' => $modulePath.'/app/Providers/'.$module.'ServiceProvider.php',
                'routes' => $routeFiles['web'],
                'abilities' => $modulePath.'/config/abilities.php',
                'navigation' => $modulePath.'/config/navigation.php',
                'database-seeder' => $modulePath.'/database/seeders/DatabaseSeeder.php',
            ],
            'scaffold_blueprint' => $resourceName === null ? null : $this->blueprints->make(
                name: $resourceName,
                module: $module,
                overrides: [
                    'plural' => $this->option('resource-plural'),
                    'route-prefix' => $this->option('route-prefix'),
                    'permission-prefix' => $this->option('permission-prefix'),
                ],
            ),
        ];
    }

    /**
     * @param  array<string, mixed>  $payload
     * @return array{created: array<int, string>, overwritten: array<int, string>, skipped: array<int, string>}
     */
    private function writeModuleShell(array $payload): array
    {
        $results = [
            'created' => [],
            'overwritten' => [],
            'skipped' => [],
        ];

        $renderedFiles = [
            $payload['files']['manifest'] => $this->renderManifest($payload),
            $payload['files']['provider'] => $this->renderProvider($payload),
            $payload['files']['routes'] => $this->renderRoutes($payload),
            $payload['files']['abilities'] => $this->renderAbilities(),
            $payload['files']['navigation'] => $this->renderNavigation($payload),
            $payload['files']['database-seeder'] => $this->renderDatabaseSeeder($payload),
        ];

        foreach ($renderedFiles as $path => $contents) {
            $this->writeFile($path, $contents, $results);
        }

        foreach ([
            $payload['module_path'].'/app/Definitions',
            $payload['module_path'].'/app/Http/Controllers',
            $payload['module_path'].'/app/Http/Requests',
            $payload['module_path'].'/app/Models',
            $payload['module_path'].'/app/Services',
            $payload['page_root'],
            $payload['module_path'].'/resources/js/components',
            $payload['module_path'].'/tests/Feature',
            $payload['module_path'].'/database/factories',
            $payload['module_path'].'/database/migrations',
            $payload['module_path'].'/lang/en',
        ] as $directory) {
            $this->files->ensureDirectoryExists($directory);
        }

        return $results;
    }

    /**
     * @return array<string, mixed>
     */
    private function writeScaffoldResource(string $module, string $resourceName): array
    {
        $exitCode = Artisan::call('scaffold:generate', [
            'name' => $resourceName,
            '--module' => $module,
            '--plural' => $this->option('resource-plural'),
            '--route-prefix' => $this->option('route-prefix'),
            '--permission-prefix' => $this->option('permission-prefix'),
            '--write' => true,
            '--force' => (bool) $this->option('force'),
            '--base-path' => $this->option('base-path'),
            '--json' => true,
        ]);

        if ($exitCode !== self::SUCCESS) {
            throw new RuntimeException('Nested scaffold generation failed.');
        }

        return [
            'exit_code' => $exitCode,
            'entity_name' => Str::headline($resourceName),
            'route_prefix' => $this->blueprints->make(
                name: $resourceName,
                module: $module,
                overrides: [
                    'plural' => $this->option('resource-plural'),
                    'route-prefix' => $this->option('route-prefix'),
                    'permission-prefix' => $this->option('permission-prefix'),
                ],
            )['route_prefix'],
        ];
    }

    /**
     * @param  array{created: array<int, string>, overwritten: array<int, string>, skipped: array<int, string>}  $results
     */
    private function writeFile(string $path, string $contents, array &$results): void
    {
        if ($this->files->exists($path)) {
            if (! $this->option('force')) {
                $results['skipped'][] = $path;

                return;
            }

            $results['overwritten'][] = $path;
        } else {
            $results['created'][] = $path;
        }

        $this->files->ensureDirectoryExists(dirname($path));
        $this->files->put($path, $contents);
    }

    private function modulePath(string $module): string
    {
        $basePath = $this->stringOption('base-path') ?? base_path();

        return rtrim($basePath, '/').'/modules/'.$module;
    }

    private function stringOption(string $key): ?string
    {
        $value = $this->option($key);

        if (! is_string($value) || trim($value) === '') {
            return null;
        }

        return trim($value);
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function renderManifest(array $payload): string
    {
        $manifest = [
            'name' => $payload['module'],
            'slug' => $payload['slug'],
            'version' => '1.0.0',
            'description' => $payload['description'],
            'namespace' => $payload['namespace'],
            'provider' => $payload['provider'],
            'author' => $payload['author'],
            'homepage' => $payload['homepage'],
            'icon' => $payload['icon'],
            'page_root' => 'resources/js/pages/'.$payload['slug'],
            'route_files' => [
                'web' => 'routes/web.php',
            ],
            'abilities_path' => 'config/abilities.php',
            'navigation_path' => 'config/navigation.php',
            'database_seeder' => $payload['database_seeder'],
        ];

        return (string) json_encode(array_filter($manifest, fn (mixed $value): bool => $value !== null), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR).PHP_EOL;
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function renderProvider(array $payload): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$payload['module']}\\Providers;

use App\\Modules\\Support\\ModuleServiceProvider;

class {$payload['module']}ServiceProvider extends ModuleServiceProvider
{
    protected function moduleSlug(): string
    {
        return '{$payload['slug']}';
    }
}
PHP;
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function renderRoutes(array $payload): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

use Illuminate\\Support\\Facades\\Route;

Route::middleware(['auth', 'user.status', 'verified', 'profile.completed'])
    ->prefix(trim((string) config('app.admin_slug'), '/'))
    ->as('app.')
    ->group(function (): void {
        // Register {$payload['module']} routes here.
    });
PHP;
    }

    private function renderAbilities(): string
    {
        return <<<'PHP'
<?php

declare(strict_types=1);

return [];
PHP;
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function renderNavigation(array $payload): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

return [
    'sections' => [
        '{$payload['slug']}_workspace' => [
            'label' => '{$payload['module']}',
            'weight' => 220,
            'area' => 'modules',
            'show_label' => true,
            'items' => [],
        ],
    ],
    'badge_functions' => [],
];
PHP;
    }

    /**
     * @param  array<string, mixed>  $payload
     */
    private function renderDatabaseSeeder(array $payload): string
    {
        return <<<PHP
<?php

declare(strict_types=1);

namespace Modules\\{$payload['module']}\\Database\\Seeders;

use Illuminate\\Database\\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
    }
}
PHP;
    }
}
