<div id="canvas">
    <div id="iframe-wrapper">
        <div id="iframe-layer">
            <div class="loading-message active">
                <div class="animation-container">
                    <div class="dot dot-1"></div>
                    <div class="dot dot-2"></div>
                    <div class="dot dot-3"></div>
                </div>
            </div>
            <div id="highlight-box">
                <div id="highlight-name">
                    <span class="name"></span>
                    <span class="type"></span>
                </div>
                <div id="section-actions">
                    <a id="add-section-btn" href="" title="Add element"><i class="ri-add-line"></i></a>
                </div>
            </div>
            <div id="select-box">
                {{-- AsteroNote Inline Editor Toolbar Container --}}
                {{-- Toolbar is dynamically generated by AsteroNote Inline plugin --}}
                <div id="wysiwyg-editor" class="asteronote-inline-container"></div>
                <div id="select-actions">
                    <a id="add-section-btn-selected" href="" title="Add element"><i class="ri-add-line"></i></a>
                    <a id="parent-btn" href="" title="Select parent"><i class="ri-corner-up-right-line"></i></a>
                    <a id="up-btn" href="" title="Move element up"><i class="ri-arrow-up-line"></i></a>
                    <a id="down-btn" href="" title="Move element down"><i class="ri-arrow-down-line"></i></a>
                    <a id="edit-code-btn" href="" title="Edit html code"><i class="ri-code-line"></i></a>
                    <a id="clone-btn" href="" title="Clone element"><i class="ri-file-copy-line"></i></a>
                    <a id="delete-btn" href="" title="Remove element"><i class="ri-delete-bin-line"></i></a>
                </div>
            </div>

            <div id="drop-highlight-box">
            </div>
        </div>
        <iframe id="iframe1" src="">
        </iframe>
    </div>
</div>
