<?php

declare(strict_types=1);

namespace App\Enums;

/**
 * NoteType - Classifications for notes
 *
 * @example
 * $note->type = NoteType::Note;
 * $note->type->label(); // "Note"
 */
enum NoteType: string
{
    case Note = 'note';       // Standard manual note by staff
    case System = 'system';   // Auto-generated by system actions

    /**
     * Get human-readable label.
     */
    public function label(): string
    {
        return match ($this) {
            self::Note => 'Note',
            self::System => 'System',
        };
    }

    /**
     * Get Remix icon class.
     */
    public function icon(): string
    {
        return match ($this) {
            self::Note => 'ri-sticky-note-line',
            self::System => 'ri-robot-line',
        };
    }

    /**
     * Get Bootstrap color class.
     */
    public function color(): string
    {
        return match ($this) {
            self::Note => 'primary',
            self::System => 'secondary',
        };
    }

    /**
     * Get all types as array for select options.
     */
    public static function options(): array
    {
        return array_map(
            fn (self $type): array => ['value' => $type->value, 'label' => $type->label()],
            self::cases()
        );
    }
}
